In [13]:
import regression as re
import imp
from numpy import * 

In [14]:
xArr,yArr = re.loadDataSet('C:\\Users\\libo\\Desktop\\learn\\machinelearninginaction\\Ch08\\abalone.txt')
re.stageWise(xArr,yArr,0.01,200)

[[0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.   0.   0.   0.01 0.   0.   0.   0.  ]]
[[0.   0.   0.   0.02 0.   0.   0.   0.  ]]
[[0.   0.   0.   0.03 0.   0.   0.   0.  ]]
[[0.   0.   0.   0.04 0.   0.   0.   0.  ]]
[[0.   0.   0.   0.05 0.   0.   0.   0.  ]]
[[0.   0.   0.   0.06 0.   0.   0.   0.  ]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.  ]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.01]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.02]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.03]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.04]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.05]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.06]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.07]]
[[0.   0.   0.01 0.06 0.   0.   0.   0.08]]
[[0.   0.   0.01 0.05 0.   0.   0.   0.08]]
[[0.   0.   0.01 0.05 0.   0.   0.   0.09]]
[[0.   0.   0.01 0.05 0.   0.   0.   0.1 ]]
[[0.   0.   0.01 0.05 0.   0.   0.   0.11]]
[[ 0.    0.    0.01  0.05  0.   -0.01  0.    0.11]]
[[ 0.    0.    0.01  0.05  0.   -0.02  0.    0.11]]
[[ 0.    0.    0.01  0.05  0.   

In [23]:
re.stageWise(xArr,yArr,0.005,1000)

[[0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.    0.    0.    0.005 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.01 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.015 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.02 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.025 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.03 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.035 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.04 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.045 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.05 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.055 0.    0.    0.    0.   ]]
[[0.   0.   0.   0.06 0.   0.   0.   0.  ]]
[[0.    0.    0.    0.065 0.    0.    0.    0.   ]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.   ]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.005]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.01 ]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.015]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.02 ]]
[[0.    0.    0.005 0.065 0.    0.    0.    0.025]]
[[0.    0.    0.005 0.065 0.    

[[ 0.     0.     0.1    0.025  0.015 -0.535  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.02  -0.535  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.025 -0.535  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.025 -0.54   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.03  -0.54   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.035 -0.54   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.04  -0.54   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.04  -0.545  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.045 -0.545  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.05  -0.545  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.05  -0.55   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.055 -0.55   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.06  -0.55   0.     0.375]]
[[ 0.     0.     0.1    0.025  0.06  -0.555  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.065 -0.555  0.     0.375]]
[[ 0.     0.     0.1    0.025  0.07  -0.555  0.     0.375]]
[[ 0.005  0.     0.1    0.025  0.07  -0.

[[ 0.035  0.     0.105  0.025  0.885 -0.745 -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.89  -0.745 -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.89  -0.75  -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.895 -0.75  -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.9   -0.75  -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.9   -0.755 -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.905 -0.755 -0.04   0.3  ]]
[[ 0.035  0.     0.105  0.025  0.91  -0.755 -0.04   0.3  ]]
[[ 0.04   0.     0.105  0.025  0.91  -0.755 -0.04   0.3  ]]
[[ 0.04   0.     0.105  0.025  0.915 -0.755 -0.04   0.3  ]]
[[ 0.04   0.     0.105  0.025  0.915 -0.755 -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.92  -0.755 -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.925 -0.755 -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.93  -0.755 -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.93  -0.76  -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.935 -0.76  -0.04   0.295]]
[[ 0.04   0.     0.105  0.025  0.94  -0.

[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.

[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.04   0.     0.105  0.025  1.295 -0.83  -0.06   0.26 ]]
[[ 0.045  0.     0.105  0.025  1.295 -0.

把这些结果与最小二乘法比较

In [28]:
xMat = mat(xArr)
yMat = mat(yArr).T
xMat = re.regularize(xMat)
yM = mean(yMat,0)
yMat = yMat - yM
weights = re.standRegres(xMat,yMat.T)
print(weights.T)

[[-1.34483792e+09  2.04542563e+11  2.48816791e+11  6.29082126e+11
   4.96529075e+10  1.04465796e+11  2.17233710e+11  1.73021578e+11]]


增加了偏差，减小了方差

In [39]:
a = [1,2,0] 
aa = var(a,0)
aa

0.6666666666666666