In [9]:
import numpy as np
u=np.array([221,196,238,187,237]).reshape([5,1])        #reshape(x,y)---x行y列。小于1则按1算
t=np.array([[21,21.3,21.2],[16.5,15.9,16.2],[25,24.8,25],[22.5,21.7,22.2],[24.8,24.3,24.4]],dtype=float)
q=1.43e-14/(u*(t*(1+0.0196*t**0.5)**3)**0.5)
print("q="+str(q))
n=q/1.602e-19+0.5
n=n.astype(np.int)      #类型转换----float/int
print("n="+str(n))
e_=q/n
print("e`="+str(e_))

q=[[1.24108882e-17 1.23123424e-17 1.23449567e-17]
 [1.60115834e-17 1.63440557e-17 1.61754967e-17]
 [1.04444498e-17 1.04921094e-17 1.04444498e-17]
 [1.41088051e-17 1.43994674e-17 1.42159463e-17]
 [1.05363799e-17 1.06586290e-17 1.06338763e-17]]
n=[[ 77  77  77]
 [100 102 101]
 [ 65  65  65]
 [ 88  90  89]
 [ 66  67  66]]
e`=[[1.61180366e-19 1.59900551e-19 1.60324113e-19]
 [1.60115834e-19 1.60235840e-19 1.60153433e-19]
 [1.60683843e-19 1.61417068e-19 1.60683843e-19]
 [1.60327331e-19 1.59994082e-19 1.59729734e-19]
 [1.59642120e-19 1.59084015e-19 1.61119337e-19]]
